# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d349d7a6fab070358da588b205307847721d86c4e8e352c9d97879ff7bdfd8a5bbc34394ed97726d799b5d3e8625047d1bfca7b826424cfc6077e1d05c33ef32

test:
  secret_key_base: 2581a0d0163daed13f7aa73ee7ed3b41db5fe74a782b278bb04d47a9a933aeed6c02e35eb9342b3d8789cd3e848362ac9bee6662fcb524711e7729a7d8e3e865

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
